name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  build-linux:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [16.x]
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#    - run: npm ci
#    - run: npm run pack
#    - run: npm run dist:linux
    
  build-macos:
  
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: Install app dependencies
      run: pnpm install
    - name: Build the app
      run: pnpm tauri build
#    - run: npm run dist:macOS
  
#  build-windows:
#
#    runs-on: windows-latest
#
#    strategy:
#      matrix:
#        node-version: [16.x]
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#    - run: npm ci
#    - run: npm run pack
#    - run: npm run dist:win
